### ISSUE TITLE
Hapi 10.4.1 TypeError: Cannot read property 'protocol' of null 

### ISSUE THREAD

**Issue by arashkay** [yayuhh/icecreambar#2]
Hi @yayuhh , I've been enjoying your plugin till tonight. I've upgraded to hapi 10.4.1 and things gone. 

**Problem**
At line 108 in icecreambar/index.js you are checking protocol using `request.server.info.protocol` which works only if hapi has single connection. 

**Solution**
With multiple connection hapi server it is an array and it's like this `server.connections[1].info.protocol`. (which is my case)

You can check their doc here http://hapijs.com/api#serverinfo

Mac, Node 4.0.0, Hapi 10.4.1
**Error log**

```
Debug: internal, implementation, error 
    TypeError: Cannot read property 'protocol' of null
    at decorateRequest (/Users/arash/Projects/tipi/api/node_modules/icecreambar/index.js:108:35)
    at internalError (/Users/arash/Projects/tipi/api/node_modules/icecreambar/index.js:33:32)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at handler (/Users/arash/Projects/tipi/api/node_modules/hapi/node_modules/kilt/lib/index.js:54:44)
    at emitTwo (events.js:92:20)
    at emit (events.js:172:7)
    at internals.Request._finalize (/Users/arash/Projects/tipi/api/node_modules/hapi/lib/request.js:475:25)
    at /Users/arash/Projects/tipi/api/node_modules/hapi/lib/request.js:455:25
    at end (/Users/arash/Projects/tipi/api/node_modules/hapi/lib/transmit.js:298:13)
    at g (events.js:260:16)
    at emitNone (events.js:72:20)
    at emit (events.js:166:7)
    at internals.Response.end (/Users/arash/Projects/tipi/api/node_modules/hapi/node_modules/shot/lib/index.js:177:10)
    at onend (_stream_readable.js:490:10)
    at g (events.js:260:16)
```

**Question**
It would be great if you can publish a new version. Can you?

**Comment by jmonster** [comment]
Absolutely -- sorry for the delay, I never got an email about this issue. If you want to make a PR I'd most certainly merge it ;) but otherwise I'll try to get to it soon.

**Comment by arashkay** [comment]
@jmonster If you can tell me whats the point of **decorateRequest** at https://github.com/yayuhh/icecreambar/blob/master/index.js#L101 Im hapi to do a PR.

**Comment by jmonster** [comment]
Rollbar assumes you're using the Express framework, so that function adds the
additional attributes that it is expecting to exist.

**Comment by jmonster** [comment]
I'm going to try to get to this in the next couple days if you don't beat me to it :D

**Comment by jmonster** [comment]
@tectual try out https://github.com/yayuhh/icecreambar/pull/3 and let me know how it goes -- you can specify the branch name in your package.json to pull it down into your project.

**disclaimer** I have not tested this outside of the projects unit tests [yet]

**Comment by arashkay** [comment]
Thanks, I will try it out and get back to you with my tests

**Comment by jmonster** [comment]
Heya @tectual  -- I'm going to close this out; any chance you ever got around to trying out the latest?

**Comment by arashkay** [comment]
It's working great. Thanks
